version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    excludes: [ ] # put task names in here which are overwritten in this file
    vars:
      NESTED_MODULES: apis controller-utils legacy-component-cli legacy-component-spec/bindings-go legacy-image-vector
      API_DIRS: '{{.ROOT_DIR}}/apis/...'
      MANIFEST_OUT: '{{.ROOT_DIR}}/apis/crds/manifests'
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/pkg/... {{.ROOT_DIR}}/test/... {{.ROOT_DIR}}/hack/testcluster/... {{.ROOT_DIR}}/apis/... {{.ROOT_DIR}}/controller-utils/... {{.ROOT_DIR}}/legacy-component-cli/... {{.ROOT_DIR}}/legacy-component-spec/bindings-go/... {{.ROOT_DIR}}/legacy-image-vector/... '
      COMPONENTS: landscaper
      REPO_URL: 'https://github.com/openmcp-project/landscaper'
      GENERATE_DOCS_INDEX: "false"
      CHART_COMPONENTS: "[]"
