//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperConfiguration) DeepCopyInto(out *LandscaperConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Controllers.DeepCopyInto(&out.Controllers)
	if in.RepositoryContext != nil {
		in, out := &in.RepositoryContext, &out.RepositoryContext
		*out = (*in).DeepCopy()
	}
	in.Registry.DeepCopyInto(&out.Registry)
	in.BlueprintStore.DeepCopyInto(&out.BlueprintStore)
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsConfiguration)
		**out = **in
	}
	in.CrdManagement.DeepCopyInto(&out.CrdManagement)
	if in.DeployItemTimeouts != nil {
		in, out := &in.DeployItemTimeouts, &out.DeployItemTimeouts
		*out = new(DeployItemTimeouts)
		(*in).DeepCopyInto(*out)
	}
	if in.LsDeployments != nil {
		in, out := &in.LsDeployments, &out.LsDeployments
		*out = new(LsDeployments)
		(*in).DeepCopyInto(*out)
	}
	if in.HPAMainConfiguration != nil {
		in, out := &in.HPAMainConfiguration, &out.HPAMainConfiguration
		*out = new(HPAMainConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperConfiguration.
func (in *LandscaperConfiguration) DeepCopy() *LandscaperConfiguration {
	if in == nil {
		return nil
	}
	out := new(LandscaperConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LandscaperConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
