//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package continuousreconcile

import (
	"github.com/openmcp-project/landscaper/apis/core/v1alpha1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousReconcileSpec) DeepCopyInto(out *ContinuousReconcileSpec) {
	*out = *in
	if in.Every != nil {
		in, out := &in.Every, &out.Every
		*out = new(v1alpha1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousReconcileSpec.
func (in *ContinuousReconcileSpec) DeepCopy() *ContinuousReconcileSpec {
	if in == nil {
		return nil
	}
	out := new(ContinuousReconcileSpec)
	in.DeepCopyInto(out)
	return out
}
