#!/bin/bash -eu

# SPDX-FileCopyrightText: Copyright OpenControlPlane contributors.
#
# SPDX-License-Identifier: Apache-2.0

if ! which make 1>/dev/null; then
  echo "> Installing make ..."
  apk add --no-cache make 1>/dev/null
fi
